app_trucks/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),

    path('workdays/', views.workdays, name='workdays'),

    path('workday/today', views.workday_today, name='workday_today'),
    path('workday/add_new', views.workday_add_new, name='workday_add_new'),

    path('workday/create/date=<_date>', views.workday_create, name='workday_create'),
    path('workday/edit/<int:workday_id>', views.workday_edit, name='workday_edit'),
    path('workday/delete/<int:workday_id>', views.workday_delete, name='workday_delete'),

    path('reports/', views.reports, name='reports'),

]

project_trucks/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_trucks.urls'))
]

app_trucks/models.py
from django.db import models
from django.contrib.auth.models import User
import calendar
from datetime import datetime, date
from django.core.exceptions import ObjectDoesNotExist

now = datetime.now()
today = now.strftime("%Y-%m-%d")


class Worker(User):

    class Meta:
        proxy = True

    @staticmethod
    def get_workers_as_choices():
        workers = Worker.objects.all()

        # save users into a list with id and name (exclude superusers)
        worker_names = []
        for worker in workers:
            if not worker.is_superuser:
                user_data = (worker.id, worker.first_name + ' ' + worker.last_name)
                worker_names.append(user_data)

        # sort by name and insert 'todos' as first element
        worker_names.sort(key=lambda x: (x[1]))
        worker_names.insert(0, (0, 'todos'))

        return worker_names


class Truck(models.Model):

    #
    # -------------------- RELATIONSHIPS ------------------------------------------------------------
    # WorkDay(workdays): one truck has many workdays

    #
    # ----------------------- FIELDS ----------------------------------------------------------------

    # basic
    name = models.CharField(max_length=200)

    # truck details
    year = models.IntegerField(null=True)  # i believe it´s the year the truck was built
    mark = models.CharField(max_length=200, null=True)
    model = models.CharField(max_length=200, null=True)
    vin = models.CharField(max_length=200, null=True)
    license_plate = models.CharField(max_length=200, null=True)

    # others
    comment = models.TextField(blank=True)

    #
    # ---------------- PROPERTIES & FUNCTIONS --------------------------------------------------------
    @staticmethod
    def get_trucks_as_choices():
        trucks = Truck.objects.all()

        # save trucks into a list with id and name
        truck_names = []
        for truck in trucks:
            truck_data = (truck.id, truck.name)
            truck_names.append(truck_data)

        # sort by name and insert 'todos' as first element
        truck_names.sort(key=lambda x: (x[1]))
        truck_names.insert(0, (0, 'todos'))

        return truck_names

    #
    # ------------------------ META -----------------------------------------------------------------
    class Meta:
        ordering = ['-year']
        verbose_name = "Truck"
        verbose_name_plural = "Trucks"

    #
    # ---------------------- STRING NAME -------------------------------------------------------------
    # string name for the class
    def __str__(self):
        return self.name if self.name else 'no_name'


class WorkDayManager(models.Manager):

    def workday_exists(self, _user, _date=today):

        # import queryset (always goes at the start of any Manager function)
        queryset = self.get_queryset()

        # if _date provided as string -> force to date object
        if type(_date) is not date:
            _date = datetime.strptime(_date, "%Y-%m-%d").date()

        # find workday
        try:
            workday = queryset.get(user=_user, date=_date)

        # workday doesn't exist -> return None
        except ObjectDoesNotExist:
            return None  # workday doesn't exist

        # workday exist -> return workday
        return workday


class WorkDay(models.Model):
    #
    # -------------------- RELATIONSHIPS ------------------------------------------------------------
    # User: one user has many workdays
    user = models.ForeignKey(User, related_name='workdays', on_delete=models.CASCADE)

    # Truck: one truck has many workdays
    truck = models.ForeignKey(Truck, related_name='workdays', on_delete=models.CASCADE)

    #
    # ----------------------- FIELDS ----------------------------------------------------------------

    # date
    date_created = models.DateTimeField(auto_now_add=True)
    date = models.DateField(default=date.today, null=True, blank=True)

    # mileage
    ini_mileage = models.IntegerField(null=True)
    end_mileage = models.IntegerField(null=True, blank=True)

    # mileage
    income = models.FloatField(null=True, blank=True, default=0)  # is only updated using method update_income

    # others
    comment = models.TextField(null=True, blank=True)

    #
    # ---------------- PROPERTIES & FUNCTIONS --------------------------------------------------------
    @property
    def name(self):
        weekday = calendar.day_name[self.date_created.weekday()]
        date_as_string = str(self.date_created).partition(' ')[0]
        return str(self.user) + ' on ' + str(self.truck) + ' ' + weekday + ' ' + date_as_string

    @property
    def name_for_user(self):
        weekday = calendar.day_name[self.date_created.weekday()]
        date_as_string = str(self.date_created).partition(' ')[0]
        return str(self.truck) + ' ' + weekday + ' ' + date_as_string

    def update_income(self, deliveries):

        # summarize payment from every delivery
        self.income = 0
        for delivery in deliveries:
            self.income += delivery.pay
        return self.income

    objects = WorkDayManager()

    #
    # ------------------------- META -----------------------------------------------------------------
    class Meta:
        ordering = ['-date']
        verbose_name = "Workday"
        verbose_name_plural = "Workdays"

    #
    # ---------------------- STRING NAME -------------------------------------------------------------
    # string name for the class
    def __str__(self):
        return self.name if self.name else 'no_name'


class CompanyManager(models.Manager):

    def select_pay_rate(self, company_id, _date=today):

        # import queryset (always goes at the start of any Manager function)
        queryset = self.get_queryset()

        # if _date provided as string -> force to date object
        if type(_date) is not date:
            _date = datetime.strptime(_date, "%Y-%m-%d").date()

        # find company
        try:
            _company = queryset.get(pk=company_id)
        except ObjectDoesNotExist:
            return None  # company doesn't exist -> No pay_rate to select

        # find pay_rates for the company
        try:
            _pay_rates = _company.pay_rates.all()
        except ObjectDoesNotExist:
            return _company.default_pay_rate  # no pay_rates for the company -> use default

        # verify if any pay_rate has a date_interval including the current_date
        for _pay_rate in _pay_rates:

            # date_interval is good -> use this pay_rate
            if _pay_rate.ini_date <= _date <= _pay_rate.end_date:
                return _pay_rate.amount

        # no date_interval was good -> use default
        else:
            return _company.default_pay_rate


class Company(models.Model):

    #
    # -------------------- RELATIONSHIPS ------------------------------------------------------------
    # Delivery(deliveries): one company has many deliveries
    # PayRate(pay_rates)  : one company has many pay_rates

    #
    # ----------------------- FIELDS ----------------------------------------------------------------

    # basic
    name = models.CharField(max_length=200)
    default_pay_rate = models.FloatField()

    # others
    comment = models.TextField(blank=True)

    #
    # ---------------- PROPERTIES & FUNCTIONS --------------------------------------------------------
    objects = CompanyManager()

    #
    # ------------------------- META -----------------------------------------------------------------
    class Meta:
        ordering = ['name']
        verbose_name = "Company"
        verbose_name_plural = "Companies"

    #
    # ---------------------- STRING NAME -------------------------------------------------------------
    # string name for the class
    def __str__(self):
        return self.name if self.name else 'no_name'


class Delivery(models.Model):
    #
    # -------------------- RELATIONSHIPS ------------------------------------------------------------
    # Company: one company has many deliveries
    company = models.ForeignKey(Company, related_name='deliveries', on_delete=models.CASCADE)

    # WorkDay: one workday has many deliveries
    workday = models.ForeignKey(WorkDay, related_name='deliveries', on_delete=models.CASCADE)

    #
    # ----------------------- FIELDS ----------------------------------------------------------------

    # basic
    pay_rate = models.IntegerField()  # copied from Company or PayRate on record creation
    amount = models.IntegerField(default=0)  # number of deliveries made

    #
    # ---------------- PROPERTIES & FUNCTIONS --------------------------------------------------------
    @property
    def name(self):
        d_id = str(self.id)
        company = str(self.company)
        user = str(self.workday.user)
        truck = str(self.workday.truck)
        d_date = str(self.workday.date_created).partition(' ')[0]
        return 'delivery id ' + d_id + ' for ' + company + ' by ' + user + ' using ' + truck + ' at ' + d_date

    @property
    def pay(self):
        return self.pay_rate * self.amount

    #
    # ------------------------- META -----------------------------------------------------------------
    class Meta:
        verbose_name = "Delivery"
        verbose_name_plural = "Deliveries"

    #
    # ---------------------- STRING NAME -------------------------------------------------------------
    # string name for the class
    def __str__(self):
        return self.name if self.name else 'no_name'


class PayRate(models.Model):

    #
    # -------------------- RELATIONSHIPS ------------------------------------------------------------
    # Company: one company has many PayRates
    company = models.ForeignKey(Company, related_name='pay_rates', on_delete=models.CASCADE)

    #
    # ----------------------- FIELDS ----------------------------------------------------------------

    # basic
    amount = models.FloatField()

app_trucks/forms.py
from django.forms import ModelForm
from app_trucks.models import *
from django.forms import Field
from django import forms
from django.core.exceptions import ValidationError


# Overwrite error messages.
Field.default_error_messages = {
    'required': "Este valor es obligatorio",
    'invalid': "Este valor no está permitido",
    'invalid_choice': u'Value %r is not a valid choice',
    'null': u'This field cannot be null.',
    'blank': u'This field cannot be blank.',
}


class WorkDayForm(ModelForm):
    class Meta:
        model = WorkDay

        readonly_fields = ('date_created',)

        fields = [
            'date',
            'truck',

            'ini_mileage',
            'end_mileage',

            'income',

            'comment',
        ]

        error_messages = {
            'ini_mileage': {
                'invalid': "Introduzca un valor numérico",
            },
            'end_mileage': {
                'invalid': 'Introduzca un valor numérico',
            },
        }


class DeliveryForm(ModelForm):
    # temp_company_name = forms.CharField()

    class Meta:
        model = Delivery
        exclude = ()


class DateForm(forms.Form):
    date = forms.DateField()


class ReportForm(forms.Form):

    #
    # ----------------------- FIELDS ---------------------------------------------------------------

    # --------- Truck Select ---------
    truck_choices = Truck.get_trucks_as_choices()
    truck = forms.ChoiceField(choices=truck_choices)

    # --------- User Select ---------
    user_choices = Worker.get_workers_as_choices()
    user = forms.ChoiceField(choices=user_choices)

    # --------- Date Pick ---------
    date_ini = forms.DateField(required=False)
    date_end = forms.DateField(required=False)

    #
    # --------------------- VALIDATION -------------------------------------------------------------
    def clean_truck(self):
        data = self.cleaned_data['truck']
        truck_choices = Truck.get_trucks_as_choices()
        truck_ids = [truck_choice[0] for truck_choice in truck_choices]
        if int(data) not in truck_ids:
            raise ValidationError(
                'El valor proprocionado no es apropiado',
                code='bad_choice',
            )

        return int(data)

    def clean_user(self):
        data = self.cleaned_data['user']
        user_choices = Worker.get_workers_as_choices()
        user_ids = [user_choice[0] for user_choice in user_choices]
        if int(data) not in user_ids:
            raise ValidationError(
                'El valor proporcionado no es apropiado',
                code='bad_choice',
            )

        return int(data)

app_trucks/templates/app_trucks/select_report.html
{%  extends 'app_trucks/includes/main.html' %}
{% load static %}

{% block content %}

{% load event_tags %}

  <!-- ======= Form Section ======= -->
  <section id="contact" class="contact pt-5">
    <div class="container" data-aos="fade-up">

      <!-- Title -->
      <div class="section-title pb-3">
        <a id="deliveries_today"></a><h2 >Reporte de Jornadas</h2>
          <!-- Greeting -->
          <p class="pb-2">
            Seleccione los datos que serán mostrados en el reporte de Jornadas Trabajadas.
              {{f.errors}}
          </p>
      </div>

      <!-- Form -->
      <div class="row">
        <div class="col">

            <!-- ERROR MESSAGE -->
            {% if messages %}
            <p class="text-muted text-center pt-2">
              {% for message in messages %}
                {% if message.message == 'form-errors' %}
                  <div class="alert alert-danger" role="alert">
                    <strong>Error. </strong>
                    Hay errores en el formulario. Por favor, corrija los errores señalados y presione Crear nuevamente.
                  </div>
                {% elif message.message == 'form-duplicated' %}
                  <div class="alert alert-danger" role="alert">
                    <strong>Error. </strong> El usuario {{ request.user.first_name }} {{ request.user.last_name }} ya tiene una jornada de trabajo para la fecha seleccionada.
                  </div>
                {% endif %}
              {% endfor %}
            </p>
            {% endif %}

          <form action="" method="post" role="form">
          {% csrf_token %}

            <!-- === First Line === -->
            <div class="form-row pt-4">

              <!-- Select Truck Field -->
              <div class="form-group col-md-4">
                <label for="truck" class="pl-2">Camión</label>
                <select id="id_truck" name="truck" class="form-control custom-select
                  {% for message in messages %}
                    {% if message.message == 'form-errors' and not f.truck.errors %}
                      is-valid
                    {% elif message.message == 'form-errors' and f.truck.errors %}
                      is-invalid
                    {% endif %}
                  {% endfor %}">
                  {% for id, name in f.fields.truck.choices %}
                    <option value={{ id }}{% if f.truck.value|add:"0" == id %} selected {% endif %} >{{name}}</option>
                  {% endfor %}
                </select>
                <small id="truckHelp" class="form-text text-muted"></small>
              </div>

              <!-- Select User Field -->
              <div class="form-group col-md-4">
                <label for="user" class="pl-2">Trabajador</label>
                <select id="id_user" name="user" class="form-control custom-select
                  {% for message in messages %}
                    {% if message.message == 'form-errors' and not f.user.errors %}
                      is-valid
                    {% elif message.message == 'form-errors' and f.user.errors %}
                      is-invalid
                    {% endif %}
                  {% endfor %}">
                  {% for id, name in f.fields.user.choices %}
                    <option value={{ id }}{% if f.user.value|add:"0" == id %} selected {% endif %} >{{name}}</option>
                  {% endfor %}
                </select>
                <small id="truckHelp" class="form-text text-muted"></small>
              </div>

            </div>

            <!-- === Second Line === -->
            <div class="form-row">

              <!-- Ini Date Field -->
              <div class="form-group col-md-4">
                <label for="id_date_ini" class="pl-2">Desde</label>
                <input type="date" name="date_ini" id="id_date_ini" aria-describedby="dateHelp" placeholder="Desde"
                       class="form-control
                       {% for message in messages %}
                           {% if message.message == 'form-errors' and not f.date_ini.errors %}
                              is-valid
                           {% elif message.message == 'form-errors' and f.date_ini.errors %}
                              is-invalid
                           {% endif %}
                       {% endfor %}"
                       value="">
              </div>

              <!-- End Date Field -->
              <div class="form-group col-md-4">
                <label for="id_date_end" class="pl-2">Hasta</label>
                <input type="date" name="date_end" id="id_date_end" aria-describedby="dateHelp" placeholder="Hasta"
                       class="form-control
                       {% for message in messages %}
                           {% if message.message == 'form-errors' and not f.date_end.errors %}
                              is-valid
                           {% elif message.message == 'form-errors' and f.date_end.errors %}
                              is-invalid
                           {% endif %}
                       {% endfor %}"
                       value="">
              </div>

            </div>

            <!-- Separator -->
            <br>
            <hr class="mt-0 pt-3">

            <!-- Submit Buttons -->
            <button type="submit" class="btn btn-primary px-4" name="make_report">Ver Reporte</button>

            <!-- Cancel Buttons -->
            <span class="pl-2"></span>
            <a class="btn btn-secondary px-3" href="{% url "dashboard" %}">Ir al Inicio</a>

          </form>

        </div>

      </div>

    </div>
  </section><!-- End Contact Section -->

{% endblock %}

app_trucks/templates/app_trucks/workday.html
{%  extends 'app_trucks/includes/main.html' %}
{% load static %}

{% block content %}

{% load event_tags %}

  <!-- ======= Form Section ======= -->
  <section id="contact" class="contact pt-5">
    <div class="container" data-aos="fade-up">

      <!-- Title -->
      <div class="section-title pb-3">
        <a id="deliveries_today"></a><h2 >Entregas del Día</h2>
          <!-- Greeting -->
          <p class="pb-2">
          {% if task == 'create_workday' %}
            <strong>{{ request.user.first_name }} {{ request.user.last_name }}!</strong> llena este formulario para guardar los datos de una nueva jornada de trabajo.
          {% elif task == 'edit_workday' %}
            <strong>{{ request.user.first_name }} {{ request.user.last_name }}!</strong> aquí puedes modificar tus entregas de la jornada.
          {% endif %}
          </p>
      </div>

      <!-- Form -->
      <div class="row">
        <div class="col">

            <!-- ERROR MESSAGE -->
            {% if messages %}
            <p class="text-muted text-center pt-2">
              {% for message in messages %}
                {% if message.message == 'form-errors' %}
                  <div class="alert alert-danger" role="alert">
                    <strong>Error. </strong>
                    Hay errores en el formulario. Por favor, corrija los errores señalados y presione Guardar nuevamente.
                  </div>
                {% elif message.message == 'form-saved' %}
                  <div class="alert alert-success" role="alert">
                    <strong>Guardado. </strong> Jornada de trabajo guardada correctamente. Haga clic para volver al
                    <a class="" href="{% url "dashboard" %}" role="button">Panel Principal</a> o revise su
                  <a class="" href="{% url "workdays" %}" role="button">Listado de Jornadas Trabajadas</a>
                  </div>
                {% elif message.message == 'form-duplicated' %}
                  <div class="alert alert-success" role="alert">
                    <strong>Error. </strong> El usuario {{ request.user.first_name }} {{ request.user.last_name }} ya tiene una jornada de trabajo creada para la fecha seleccionada.
                  </div>
                {% endif %}
              {% endfor %}
            </p>
            {% endif %}

          <form action="" method="post" role="form">
          {% csrf_token %}

            <!-- === First Line === -->
            <div class="form-row">

              <!-- Date Field -->
              <div class="form-group col-md-4">
                <label for="id_date" class="pl-2">Fecha</label>
                <input type="date" name="date" readonly id="id_date" aria-describedby="dateHelp" placeholder="Fecha"
                       class="form-control
                       {% for message in messages %}
                           {% if message.message == 'form-duplicated' %}
                              is-invalid
                           {% elif message.message == 'form-errors' and not f.date_created.errors %}
                              is-valid
                           {% elif message.message == 'form-errors' and f.date_created.errors %}
                              is-invalid
                           {% endif %}
                       {% endfor %}"
                       value="{{ date }}">
              </div>

            </div>

            <!-- === Second Line === -->
            <div class="form-row">

              <!-- Truck Field -->
              <div class="form-group col-md-4">
                <label for="truck_name" class="pl-2">Camión</label>
                <select id="id_truck" name="truck" class="form-control custom-select
                  {% for message in messages %}
                    {% if message.message == 'form-errors' and not f.truck.errors %}
                      is-valid
                    {% elif message.message == 'form-errors' and f.truck.errors %}
                      is-invalid
                    {% endif %}
                  {% endfor %}">
                  {% for id, name in f.fields.truck.choices|slice:"1:" %}
                    <option value={{ id }}{% if f.truck.value|add:"0" == id %} selected {% endif %} >{{name}}</option>
                  {% endfor %}
                </select>
                <small id="truckHelp" class="form-text text-muted"></small>
              </div>

            </div>

            <!-- === Third Line === -->
            <div class="form-row">

              <!-- Ini Mileage Field -->
              <div class="form-group col-md-4">
                <label for="id_ini_mileage" class="pl-2">Contador inicial</label>
                <input type="number" id="id_ini_mileage" aria-describedby="ini_mileageHelp" placeholder="Contador inicial"
                       class="form-control
                       {% for message in messages %}
                           {% if message.message == 'form-errors' and not f.ini_mileage.errors %}
                              is-valid
                           {% elif message.message == 'form-errors' and f.ini_mileage.errors %}
                              is-invalid
                           {% endif %}
                       {% endfor %}"
                       value="{{f.ini_mileage.value|default_if_none:""}}"
                       name="{{f.ini_mileage.name}}"
                       maxlength="{{f.ini_mileage.maxlength}}">
                       {% for message in messages %}
                           {% if message.message == 'form-errors' and f.ini_mileage.errors %}
                              <small class="invalid-feedback pb-0">{{f.ini_mileage.errors}}</small>
                           {% else %}
                               <small id="ini_mileageHelp" class="form-text text-muted pl-2"></small>
                           {% endif %}
                       {% endfor %}
              </div>

              <!-- End Mileage Field -->
              <div class="form-group col-md-4">
                <label for="id_end_mileage" class="pl-2">Contador final</label>
                <input type="number" id="id_end_mileage" aria-describedby="end_mileageHelp" placeholder="Contador final"
                       class="form-control
                       {% for message in messages %}
                           {% if message.message == 'form-errors' and not f.end_mileage.errors %}
                              is-valid
                           {% elif message.message == 'form-errors' and f.end_mileage.errors %}
                              is-invalid
                           {% endif %}
                       {% endfor %}"
                       value="{{f.end_mileage.value|default_if_none:""}}"
                       name="{{f.end_mileage.name}}"
                       maxlength="{{f.end_mileage.maxlength}}">
                       {% for message in messages %}
                           {% if message.message == 'form-errors' and f.end_mileage.errors %}
                              <small class="invalid-feedback pb-0">{{f.end_mileage.errors}}</small>
                           {% else %}
                               <small id="end_mileageHelp" class="form-text text-muted pl-2"></small>
                           {% endif %}
                       {% endfor %}
              </div>

            </div>

            <!-- Separator -->
            <br>
            <hr class="mt-0">

            <!-- ====== SET COMPANIES ====== -->
            <h5 class="pb-2">Tiendas</h5>

            <!-- === Form Set === -->
            <div class="form-row">

              {{ fs.management_form }}

              {% for form in fs %}

                <!-- Deliveries for Store -->
                <div class="form-group col-md-4">
                  <label for="store1" class="pl-2">{{form.company.value|company_verbose}}</label>
                  <div class="input-group mb-0">
                    <input type="number" class="form-control
                       {% for message in messages %}
                        {% if message.message == 'form-errors' and not form.amount.errors %}
                          is-valid
                        {% elif message.message == 'form-errors' and form.amount.errors %}
                          is-invalid
                        {% endif %}
                       {% endfor %}"
                       value={{form.amount.value}}
                       name="deliveries-{{forloop.counter0}}-amount"
                       id="id_deliveries-{{forloop.counter0}}-amount"
                       placeholder={{form.amount.value}}
                       aria-label={{form.amount.value}}
                       aria-describedby="store{{forloop.counter0}}Help">
                    <div class="input-group-append">
                      <span class="input-group-text" id="store{{forloop.counter0}}Help"><small>{{form.pay_rate.value|default_if_none:0}} USD</small></span>
                    </div>
                  </div>
                </div>



                <!-- Fields with additional data for Deliveries -->
                <input type="hidden" name="deliveries-{{forloop.counter0}}-company" value={{form.company.value}} id="id_deliveries-{{forloop.counter0}}-company">
                <input type="hidden" name="deliveries-{{forloop.counter0}}-pay_rate" value={{form.pay_rate.value|default_if_none:0}} id="id_deliveries-{{forloop.counter0}}-pay_rate">

                <!-- Fields for Delete functionality data -->
                <input type="hidden" name="deliveries-{{forloop.counter0}}-DELETE" id="id_deliveries-{{forloop.counter0}}-DELETE">
                <input type="hidden" name="deliveries-{{forloop.counter0}}-workday" id="id_deliveries-{{forloop.counter0}}-workday">
                {% if task == 'create_workday' %}
                  <input type="hidden" name="deliveries-{{forloop.counter0}}-id" id="id_deliveries-{{forloop.counter0}}-id">
                {% elif task == 'edit_workday' %}
                  <input type="hidden" name="deliveries-{{forloop.counter0}}-id" value={{form.id.value}} id="id_deliveries-{{forloop.counter0}}-id">
                {% endif %}

              {% endfor %}

            </div>

            {% if task == 'edit_workday' %}

            <!-- Separator -->
            <br>
            <hr class="mt-0 pt-3">

            <!-- Total -->

            <p>TOTAL : <span id="summary-value">{{income}}</span></p>

            {% endif %}

            <!-- Separator -->
            <br>
            <hr class="mt-0 pt-3">

            <!-- Submit Buttons -->
            {% if task == 'create_workday' %}
              <button type="submit" class="btn btn-primary px-4" name="create-workday">Guardar</button>
            {% elif task == 'edit_workday' %}
              <button type="submit" class="btn btn-primary px-4" name="edit-workday">Guardar</button>
            {% endif %}

            <!-- Cancel Buttons -->
            <span class="pl-2"></span>
            <a class="btn btn-secondary px-3" href="{% url "dashboard" %}">Ir al Inicio</a>
            <span class="pl-2"></span>
            <a class="btn btn-secondary" href="{% url "workdays" %}">Ir al Listado de Jornadas</a>
          </form>

        </div>

      </div>

    </div>
  </section><!-- End Contact Section -->

{% endblock %}